version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8-jdk
    steps:
      - checkout
      - run:
         name: Build
         command: |
           -ant -lib lib/ Build: 
          timeout: 600

