version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
  steps:
      - checkout
      - run:
         name: build
         command: ant -f builds/build.xml -lib build/lib/ deploy:
