version: 2
jobs:
  build:
    docker:
      - image: atsnngs/force-com:latest
    steps:
       - run:
         name: Deploy
       - run:
    	shell: /bin/sh
    	command: |
      		ant -lib lib/ Build: 
      		
